id = "smarty"
name = "Smarty"
description = "Smarty templating support"
version = "0.0.1"
schema_version = 1
authors = ["gmnz <28140754+gmnz@users.noreply.github.com>"]
repository = "https://github.com/gmnz/zed-smarty"

[grammars.smarty]
repository = "https://github.com/Kibadda/tree-sitter-smarty"
commit = "17432b6dd8ce803d921333ee6ac4ce3132740197"
