name = "Smarty"
grammar = "smarty"
path_suffixes = ["*.tpl"]

block_comment = ["{*", "*}"]

autoclose_before = ";:.,=}])>"


brackets = [


    { start = "{", end = "}", close = true, newline = true },


    { start = "[", end = "]", close = true, newline = true },


    { start = "(", end = ")", close = true, newline = true },


]
